scno	= $00
numlif	= $01

vara	= $02			; general-purpose variable.
varb	= $03			; general-purpose variable.
varc	= $04			; general-purpose variable.
vard	= $05			; general-purpose variable.
vare	= $06			; general-purpose variable.
varf	= $07			; general-purpose variable.
varg	= $08			; general-purpose variable.
varh	= $09			; general-purpose variable.
vari	= $0a			; general-purpose variable.
varj	= $0b			; general-purpose variable.
vark	= $0c			; general-purpose variable.
varl	= $0d			; general-purpose variable.
varm	= $0e			; general-purpose variable.
varn	= $0f			; general-purpose variable.
varo	= $10			; general-purpose variable.
varp	= $11			; general-purpose variable.
varq	= $12			; general-purpose variable.
varr	= $13			; general-purpose variable.
vars	= $14			; general-purpose variable.
vart	= $15			; general-purpose variable.
varu	= $16			; general-purpose variable.
varv	= $17			; general-purpose variable.
varw	= $18			; general-purpose variable.
varz	= $19			; general-purpose variable.

charx	= $1a
chary	= $1b

clock	= $1c
varrnd	= $1d
varobj	= $1e
varopt	= $1f
varblk	= $20
nexlev	= $21
restfl	= $22
deadf	= $23
gamwon	= $24
dispx	= $25
dispy	= $26

contrl	= $27
joyval	= $28
frmno	= $29

loopa	= $2a
loopb	= $2b
loopc	= $2c
FontPtr	= $2d

scraddr	= $2f
fntaddr	= $31
tileaddr= $33
bufaddr	= $35

tmp	= $37
scr_l	= $39
scr_r	= $3b
scr_txt	= $3d

xtmp	= $3f
spcnt	= $40
spptr	= $41
seed	= $42

ccnt	= $43
flag	= $44
rcol	= $45
rrow	= $46

combyt	= $47
comcnt	= $48
prtmod	= $49
qscnt	= $4a

sprptr	= $4b
sprcnt	= $4c

skptr	= $4d
sktptr	= $4f
tmproom	= $50
ogptr	= $52

.if mflag
Tmpaddr	= $54
bwid	= $56
blen	= $57
btop	= $58
blft	= $59
.endif

.if pflag
shrctr	= $5a
explcnt	= $5b
seed3	= $5c
.endif

